- .github/ISSUE_TEMPLATE/feat.yml
- .github/ISSUE_TEMPLATE/fix.yml
- .github/ISSUE_TEMPLATE/update.yml
- Github 이슈 템플릭 작성
- Feat 이슈 템플릿 추가
- Update 이슈 템플릿 추가
- Fix 이슈 템플릿 추가
- close  #1
> [feat] feat/update/fix 이슈템플릿 추가 #1

- Source/Splatoon/Character/SplatoonCharacter.cpp
- Source/Splatoon/Character/SplatoonCharacter.h
- Source/Splatoon/Guns/BaseGun.cpp
- Source/Splatoon/Guns/BaseGun.h
-총알 발사 타이머 Gun->charater
-
- close #21
> [feat] 캐릭터 무기 생성 및 작동 #21

- Source/Splatoon/Character/SplatoonCharacter.cpp
- Source/Splatoon/Guns/BaseGun.cpp
- Source/Splatoon/Guns/BaseGun.h
> [feat] 2차 수정 #21

- Content/Map/Level01.umap
- Content/Resources/Materials/AutomotiveMaterials/MaterialFunctions/MF_Imperfections.uasset
- Content/Resources/Materials/AutomotiveMaterials/MaterialFunctions/MF_Triplanar_Mask.uasset
- Content/Resources/Materials/AutomotiveMaterials/MaterialFunctions/MF_Triplanar_UVs.uasset
- Content/Resources/Materials/AutomotiveMaterials/Materials/Textures/T_Imperfections_Dust_01_Mask.uasset
- Content/Resources/Materials/AutomotiveMaterials/Materials/Textures/T_Imperfections_FingerPrints_Mask2.uasset
- Content/Resources/Materials/AutomotiveMaterials/Materials/Textures/T_Imperfections_Stains_Mask.uasset
- Content/Resources/Materials/AutomotiveMaterials/Materials/Textures/T_Imperfections_Wipe_Mask.uasset
- Content/Resources/Materials/Street01/Materials/M_Street01.uasset
- Content/Resources/Materials/Street01/Textures/T_Street01_BaseColor.uasset
- Content/Resources/Materials/Street01/Textures/T_Street01_Normal.uasset
- Content/Resources/Materials/Street01/Textures/T_Street01_OcclusionRoughnessMetallic.uasset
- Content/Resources/Meshes/LevelPrototyping/Materials/MI_LDGrid_Local_Grey.uasset
- Content/Resources/Meshes/LevelPrototyping/Materials/MI_Solid_Blue.uasset
- Content/Resources/Meshes/LevelPrototyping/Materials/MI_Solid_Orange.uasset
- Content/Resources/Meshes/LevelPrototyping/Materials/MI_Solid_Purple.uasset
- Content/Resources/Meshes/LevelPrototyping/Materials/M_LDGrid_Local.uasset
- Content/Resources/Meshes/LevelPrototyping/Materials/M_Solid.uasset
- Content/Resources/Meshes/LevelPrototyping/Materials/TechArt/MF_CheapLF_Vec2.uasset
- Content/Resources/Meshes/LevelPrototyping/Materials/TechArt/MF_LDGrid_Triplanar.uasset
- Content/Resources/Meshes/LevelPrototyping/Meshes/BP_Corver_1_5M.uasset
- Content/Resources/Meshes/LevelPrototyping/Meshes/BP_SideWall.uasset
- Content/Resources/Meshes/LevelPrototyping/Meshes/SM_Dummy_ChamferCube.uasset
- Content/Resources/Meshes/LevelPrototyping/Meshes/SM_Dummy_Cube_01.uasset
- Content/Resources/Meshes/LevelPrototyping/Meshes/SM_Dummy_QuarterCylinder_01.uasset
- Content/Resources/Meshes/LevelPrototyping/Meshes/SM_Dummy_Ramp_01.uasset
- Content/Resources/Meshes/LevelPrototyping/Meshes/SM_Dummy_Stair_1m_01.uasset
- Content/Resources/Meshes/LevelPrototyping/Meshes/SM_MeleeMonster_Cube.uasset
- Content/Resources/Meshes/LevelPrototyping/Meshes/SM_RangedMonster_Cube.uasset
- Content/Resources/Meshes/LevelPrototyping/Textures/T_Grid.uasset
- 1레벨 구조 디자인
<br>
- 파란색 점 : 풍선
- 노란색 점 : 근접 몬스터
- 보라색 점 : 원거리 몬스터
- 시스템
- 풍선
- 조개알
- 몬스터 1,2,3
- 건축물
- 엄폐물 
- 플레이어
- 플레이어 점프 거리 / 오징어 점프 거리
- 플레이어 높이
- close #38
> [feat] Level Design (프로토 타입) #38

- Content/Blueprints/Guns/BP_Splattershot.uasset
- Content/Resources/Character/export.uasset
- Content/Resources/Character/export_Skeleton.uasset
- Content/Resources/Meshes/Guns/Splattershot/SM_Splattershot.uasset
- Source/Splatoon/Bullets/BaseBullet.cpp
- Source/Splatoon/Character/SplatoonCharacter.cpp
- Source/Splatoon/Guns/BaseGun.cpp
캐릭터가 올바르게 무기를 부착할 수 있도록 구현
스켈레탈 메시에 소켓 추가로 구현
- close #42
> [feat] 캐릭터 무기 부착 #42

- Source/Splatoon/Bullets/BaseBullet.cpp
- Source/Splatoon/Bullets/BaseBullet.h
- Source/Splatoon/Bullets/StandardBullet.cpp
- Source/Splatoon/Character/SplatoonCharacter.cpp
화면 중앙으로 총알이 이동 되도록 구현
카메라의 포워드 벡터로부터 특정 거리(25M)에 위치한 벡터 값으로 이동 되도록 구현
- close  #37
> [feat] 총알 방향 조정 #37

- Content/Blueprints/Character/BP_SplatoonCharacter.uasset
- Content/Blueprints/Guns/BP_Splattershot.uasset
- Content/Resources/Character/splatoon-squid-form/Meterial/Body.uasset
- Content/Resources/Character/splatoon-squid-form/Meterial/Eyes.uasset
- Content/Resources/Character/splatoon-squid-form/Meterial/UnderEyes.uasset
- Content/Resources/Character/splatoon-squid-form/SplatoonSquid.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Body_Base_Color.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Body_Metallic.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Body_Mixed_AO.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Body_Normal_OpenGL.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Body_Roughness.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Eyes_Base_Color.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Eyes_Metallic.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Eyes_Mixed_AO.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Eyes_Normal_OpenGL.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/Eyes_Roughness.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/UnderEyes_Base_Color.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/UnderEyes_Metallic.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/UnderEyes_Mixed_AO.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/UnderEyes_Normal_OpenGL.uasset
- Content/Resources/Character/splatoon-squid-form/Texture/UnderEyes_Roughness.uasset
- Source/Splatoon/Bullets/PaintDecal.cpp
- Source/Splatoon/Bullets/PaintDecal.h
- Source/Splatoon/Character/SplatoonCharacter.cpp
- Source/Splatoon/Character/SplatoonCharacter.h
- Source/Splatoon/Splatoon.Build.cs
- 레이캐스트
- 오징어 메쉬
- 변신
-
- close #34
> [feat] 레이캐스트, 변신 #34

- Content/Blueprints/LevelActors/BP_Balloon.uasset
- Content/Blueprints/LevelActors/BP_Pearl.uasset
- Content/Blueprints/LevelActors/FloatingCurve.uasset
- Content/Resources/Materials/M_Balloon.uasset
- Content/Resources/Materials/M_Balloon_Rope.uasset
- Content/Resources/Meshes/SM_Balloon.uasset
- Content/Resources/Meshes/SM_Balloon_Rope.uasset
- Content/Resources/Texture/T_Balloon.uasset
- Content/Resources/Texture/T_Balloon_Rope.uasset
- Source/Splatoon/Bullets/BaseBullet.cpp
- Source/Splatoon/Bullets/StandardBullet.cpp
- Source/Splatoon/Games/SplatoonGameMode.cpp
- Source/Splatoon/Games/SplatoonGameMode.h
- Source/Splatoon/LevelActors/Balloon.cpp
- Source/Splatoon/LevelActors/Balloon.h
- Source/Splatoon/LevelActors/Pearl.cpp
- Source/Splatoon/LevelActors/Pearl.h
- Source/Splatoon/Splatoon.Build.cs
- 풍선, 진주알
- Balloon: 둥실거리는 움직임, Bullet 오버랩 시 파괴, 파괴 시 나이아가라 호출 및 Pearl 생성 (나이아가라 수정 필요)
- Pearl: 플레이어 오버랩 시 파괴되며(습득) 점수 증가 (습득 나이아가라 작업 필요)
- GameMode: 레벨에 남아있는 Balloon 개수 기록, Pearl 습득 시 점수 증가
- close #51
> [feat] 풍선 및 진주알 작업 #51

- Config/DefaultEngine.ini
- Content/Blueprints/Bullets/BP_StandardBullet.uasset
- Content/Blueprints/Character/BP_PlayerChacter.uasset
- Content/Blueprints/Games/BP_MainGameMode.uasset
- Content/Blueprints/Guns/BP_MainGun.uasset
- Content/Blueprints/LevelActors/BP_Balloon.uasset
- Content/Map/Level01.umap
- Source/Splatoon/Character/SplatoonCharacter.cpp
> [Test] 레벨 플레이 테스트 #47

- Content/Blueprints/Character/BP_SplatoonCharacter.uasset
- Source/Splatoon/Character/SplatoonCharacter.cpp
- Source/Splatoon/Character/SplatoonCharacter.h
- Source/Splatoon/Guns/BaseGun.cpp
- 기본적인 데미지 함수
- 총의 재장전 함수 불러오기
- 총의 재장전 타이머에 조건문
-
- close #53
> [feat]기본적인 데미지/ 재장전 #53

- Config/DefaultEngine.ini
- Source/Splatoon/Bullets/BaseBullet.cpp
- 총알끼리 충돌하는 문제 발생
- Object Channel 추가: Bullet
- Preset 추가: Bullet
- close #61
> [fix] 총알 충돌 수정 #61

- Source/Splatoon/Character/SplatoonCharacter.cpp
- Source/Splatoon/Character/SplatoonCharacter.h
- Source/Splatoon/LevelActors/DropCheckBox.cpp
- Source/Splatoon/LevelActors/DropCheckBox.h
- 맵 밖으로 나가게 되었을 경우 낙사 시키는 콜리전 박스
-
- close #60
> [feat]낙사 #60

- Content/Resources/Materials/HitEffect/MI_PaintHitEffect.uasset
- Content/Resources/Materials/HitEffect/M_PaintHitEffect.uasset
- Content/Resources/Materials/HitEffect/rain_drops.uasset
- Content/UI/HitEffect/WBP_HitEffect.uasset
- Source/Splatoon/Character/SplatoonCharacter.cpp
- Source/Splatoon/Character/SplatoonCharacter.h
- Source/Splatoon/Splatoon.Build.cs
- 피격 이펙트 UI 구현
- 피격시 이펙트 발생
- 몬스터 공격 이벤트 구현 시 이펙트 적용 예정 
- close #59
> [feat] 피격 이펙트 UI #59

- Content/Resources/Image/HUD/BulletLoadingFillImg.uasset
- Content/UI/BulletGauge/WBP_BulletLoading.uasset
- 장전 UI 게이지에 퍼센트가 제대로 반영되지 않는 문제 수정
- UI 이미지와 progress bar를 따로 만들어 위치 조정함
- close #84
> [fix] 장전 UI 게이지 수정 #84

- Content/Resources/Image/GameOver/BeautyPlus-image-extender__2_.uasset
- Content/Resources/Image/GameOver/Splatoon-Photoroom.uasset
- Content/Resources/Image/GameOver/Splatoon-Photoroom1.uasset
- Content/Resources/Image/GameOver/Splatoon-Photoroom2.uasset
- Content/Widget/GameOver/WBP_GameOver.uasset
- Source/Splatoon/Character/SplatoonCharacter.cpp
- Source/Splatoon/Games/SplatoonGameState.cpp
- Source/Splatoon/Games/SplatoonGameState.h
- Source/Splatoon/Players/SplatoonPlayerController.cpp
- Source/Splatoon/Players/SplatoonPlayerController.h
> [feat] 사망위젯 #69

- Config/DefaultEngine.ini
- Content/Resources/Image/HUD/BalloonUIBackground.uasset
- Content/Resources/Image/HUD/ScoreBackground.uasset
- Content/Resources/Materials/M_BulletGauge.uasset
- Content/UI/BulletGauge/WBP_BalloonCount.uasset
- Content/UI/BulletGauge/WBP_BulletGauge.uasset
- Content/UI/BulletGauge/WBP_BulletLoading.uasset
- Content/UI/BulletGauge/WBP_Score.uasset
- Content/UI/WBP_HUD.uasset
- Source/Splatoon/Games/SplatoonGameInstance.cpp
- Source/Splatoon/Games/SplatoonGameInstance.h
- Source/Splatoon/Games/SplatoonGameMode.cpp
- Source/Splatoon/Games/SplatoonGameMode.h
- Source/Splatoon/Games/SplatoonGameState.cpp
- Source/Splatoon/Games/SplatoonGameState.h
- HUD 작업 완료
- 점수 및 풍선 UI 완료
- 머티리얼 색 플레이어 데칼 색에 맞춰 수정
- close #104
> [feat] 점수 및 풍선 개수 UI #104

- Content/Map/Level01.umap
- Content/Map/Level02.umap
- 2레벨 몬스터 배치
- 각 스테이지별 몬스터 배치
- close #102
> [feat] 2레벨 몬스터 배치 #102

- Content/Map/MainLevel.umap
- Content/Resources/Sound/Music/3-02__Octo_Canyon_.uasset
- Content/Widget/GameOver/WBP_GameOver.uasset
- Source/Splatoon/Players/SplatoonPlayerController.cpp
> Feet/94 메인레벨카메라

- Content/Map/NewMap.umap
- Content/Resources/Materials/HitEffect/M_PaintHitEffect.uasset
- Content/Widget/HitEffect/WBP_HitEffect.uasset
- HitEffect 머티리얼 및 위젯블루프린트 수정
- HitEffect 머티리얼: CentralRadius 변수화 / Clamp 범위 수정
- HitEffect 위젯블루프린트: 체력 퍼센트가 int값으로 들어와 float으로 수정 / 브러쉬를 DynamicMaterialInstance로 변경해 CentralRadius 직접 설정 / 애니메이션 재생 시간 조정
- close #110
> [fix] HitEffect 수정 #110

- Content/Blueprints/LevelActors/BP_ClearBox.uasset
- Content/Map/Level02.umap
- Content/Resources/Niagara/Portal/NS_ClearBox.uasset
- Content/Resources/Niagara/Portal/NS_Portal.uasset
- Content/Resources/Trophy/Base_black.uasset
- Content/Resources/Trophy/Cylinder.uasset
- Content/Resources/Trophy/Material_001.uasset
- Content/Resources/Trophy/Plane.uasset
- Content/Resources/Trophy/Star.uasset
- Content/Resources/Trophy/gold.uasset
- Content/UI/BulletGauge/WBP_BalloonCount.uasset
- Content/UI/BulletGauge/WBP_Score.uasset
- Source/Splatoon/LevelActors/ClearBox.cpp
- Source/Splatoon/LevelActors/ClearBox.h
- Source/Splatoon/LevelActors/Portal.cpp
- Source/Splatoon/LevelActors/Portal.h
- 클리어박스 및 허드UI 수정
- 클리어박스: 풍선 모두 파괴 시 나이아가라 및 트로피 스태틱메쉬 Visible
- 허드UI: 폰트 변경 / 점수 자릿수 5자리로 변경
- close #118
> [feat] 클리어박스 및 UI 수정 #118

- Content/Blueprints/Players/BP_SplatoonPlayerController.uasset
- Content/Map/NiagaraTestLevel.umap
- Content/Widget/ClearWidget/WBP_Clear.uasset
- Content/Widget/MainMenu/WBP_MainMenu.uasset
- Add clear widget
- Add clear widget
- close #127
> [feat] clear widget #127
